# Generated by Django 3.2.4 on 2021-07-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart', to='products.Product'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
